

- name: postgresql
  docker_container:
    name: postgresql
    image: postgresql:latest
    restart: yes
    ports:
      - 5432:5432
    networks:
      - name: postgresql_net 
    volumes:
      - postgre-data


- name: postgresql user
  postgresql_user: 
    db: database
    name: db_user
    password: db_passwd



