

- name: "graylog"
    
  docker_service:
    project_name: graylog
    definition:
      version: "3.0" 
      services:
        graylog:
          image: graylog/graylog:3.0
          environment:
            - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
            - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
          links:
            - postgresql:db
          depends_on:
            - postgresql            
          ports:
            # web interface and REST API
            - 9000:9000
            # Syslog TCP
            - 1514:1514
            # Syslog UDP
            - 1514:1514/udp
            # GELF TCP
            - 12201:12201
            # GELF UDP
            - 12201:12201/udp
              



